### ISSUE TITLE
text artifacts from 2016 on mobile

### ISSUE THREAD

**Issue by brianblain** [jazzto/2018#10]
Under "Festival" (on mobile only) there's a blurb about 2016 festival.

Also, there have been complaints from customers who were searching for certain artists and coming up with a jazz festival play (except it was for a previous year - not always indicated)

I don't think there's anything we can do about that space junk is there?

**Comment by andrewfn** [comment]
I'm trying to reproduce the blurb about 2016 festival on mobile under festival, but I can't see it.
Is it under a sub menu?
Are you referring to the "artist submissions" ?

Regarding the artists, if you can give me an example, then I will try and track it down. We have a bot that goes around cleaning up old stuff, and I could check if it has missed something.

**Comment by andrewfn** [comment]
> Brian wrote:
> The link that has 2016 dates is 
> http://m.torontojazz.com/festival

Yes, you are right. And it is on the main site as well:
http://torontojazz.com/festival
I guess nobody has updated it for this year.

**Comment by andrewfn** [comment]
Looks good now.
I think people can get to it if they click very quickly on the festival menu before the rest of the items have had time to load up.
