### ISSUE TITLE
photo page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2018#11]
I have created a new flickr group but having trouble remembering how we did this.  I think last time I was already using a discontinued feature and now I cant even see where to get the embed code.  I found this old code from previous yeaR (OR MAYBE OLDER):

<div style='position: relative; padding-bottom: 76%; height: 0; overflow: hidden;'><iframe id='iframe' src='//flickrit.com/slideshowholder.php?height=75&size=big&count=100&group=2833055@N21&click=true&caption=on&credit=1&thumbnails=0&transition=0&layoutType=responsive&sort=0' scrolling='no' frameborder='0'style='width:100%; height:100%; position: absolute; top:0; left:0;' ></iframe></div>

I'm sure your recollection is better than mine (as usual)

Flickr login:  tojazz@yahoo.com
pass: ladyday+4
group: 2018 TD Toronto Jazz Festival

**Comment by andrewfn** [comment]
Ok, I'll take a look at that.

**Comment by andrewfn** [comment]
I used this tool to create an embed code: http://flickrslidr.com
You can see the results here: http://torontojazz.com/2018-photos
If you want to make it bigger, we can remove the sidebars for just that page.
