### ISSUE TITLE
linking new photo page to menu

### ISSUE THREAD

**Issue by brianblain** [jazzto/2018#12]
or copy code?  Anyway could you make those 3 measly pics live and we'll start adding some

**Comment by andrewfn** [comment]
Done it.
I can remove the page title at the top if you like.

**Comment by brianblain** [comment]
If removing title would give us a little more real estate for the photos, go ahead.  Will it mask the info button? It would be good if it (the "i" button) was more obvious to display captions (though many photos don't have captions so I wouldn't want it as default)

On mobile you get the message "Parent fullscreen not available..." when you double click on photo.  Is there a way we could enable a larger view?

Could we get the slideshow to rotate automatically?

**Comment by andrewfn** [comment]
I had to hack the code quite deeply, but now I can control it.
- Have made it take the full page, (but can't make the info button any larger)
- On a 5-second timer for rotating the slides --tell me if you want that changed
- Mobile works for me now. Give it a try.

**Comment by andrewfn** [comment]
I have managed to make the background to the info button larger and more prominent. You'll have to shift-refresh to reload the page.

**Comment by brianblain** [comment]
great! I notice the rotation does not resume if you click to go back to see a pic.  I guess that's only natural.  Don't worry about it. Lookin good

**Comment by brianblain** [comment]
ooops - the info button not working on my iphone

**Comment by andrewfn** [comment]
Same on my phone, but i found if I hold the button for a couple of seconds then it works. Weird.

**Comment by brianblain** [comment]
yes I see.  Only works when it's not rotating

**Comment by brianblain** [comment]
there are 44 photos in the group pool but only the most recent 30 display on the website.  I saw a reference to a limit of 30 but that was a limit on the number of groups you can post an image to.  Is there some kind of limit to our player?  I will no start eliminating some of the repetitive photos

**Comment by andrewfn** [comment]
Yes you are right.
I can actually only see 34 on https://www.flickr.com/groups/3166682@N21
Maybe there is a delay before they get to the gallery. I'll keep checking.

**Comment by brianblain** [comment]
I removed 10 from the pool

**Comment by andrewfn** [comment]
Apparently the limit of 30 is because it can lock up your browser to have many more images in the slider. I found some discussion on it.
