### ISSUE TITLE
diplaying more than 30 photos

### ISSUE THREAD

**Issue by brianblain** [jazzto/2018#14]
I've been culling a lot of photos from the flick group but we'll end up with 90 or so (though only 30 display on slideshow)  What's the best way to show all 90?

**Comment by andrewfn** [comment]
We could put three slideshows one above the other if that would work. There
seems to be a hard limited of 30 per gallery

**Comment by andrewfn** [comment]
I think I might have found a way to raise the limit to 100
Stand by...

**Comment by andrewfn** [comment]
Done. You'll have to shift-reload to clear your cache but it works.
