### ISSUE TITLE
accept videos/links on submissions page?

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2018#16]
Hi Andrew,

Increasingly applicants to the jazz festival are asking about including video as part of their submission. How would you recommend we handle this?  Currently the submission form accepts audio only.  Perhaps we change it to accept audio uploads AND/OR video links?

Let me know what you think.

Thanks.

**Comment by andrewfn** [comment]
Hi Josh,
Actually video is better -- the audio is a bit of a pain for us because we fill up our storage with Gb of files, but the video would be hosted by youtube etc and we only need to store a link.
The same control could not be used for upload as well as a link, but we could provide a place for three video links. I could rough something out on the dev site and show it to you.

**Comment by joshgrossman** [comment]
Sounds good - thanks Andrew.  Would still like to keep the option for audio upload - it works well for my purposes and not all artists have good video - but the option of either or would be good.

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Canada in 2018 (BizBash)

**Comment by joshgrossman** [comment]
Hi Andrew,

With the 2019 Festival now wrapped up, I was hoping we could revisit the thread below.  Can we add an area on the artist submission form (http://torontojazz.com/content/artist-submissions <http://torontojazz.com/content/artist-submissions>) for links to video?  I would then suggest creating an audio/video section (as opposed to separate sections for audio and video).  I imagine it would read something like:

Audio and/or Video Samples
Provide up to three audio and/or video samples below.
Audio samples must be in mp3 format with a maximum file size of 10 Mb
Video samples must be via links to either YouTube or Vimeo
We strongly recommend that you provide at least three contrasting samples.

Let me know if this is doable…

Thanks.

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Canada in 2018 (BizBash)

**Comment by andrewfn** [comment]
Yes this looks good and I will get back to you on the feasibility

**Comment by joshgrossman** [comment]
Hi Andrew - just wanted to check in on this.  Let me know...

Thanks!

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Toronto in 2019 (BizBash)

**Comment by andrewfn** [comment]
Hi Josh,
Sorry I have been delayed on this (three weeks in Europe), but I am back
now and working on it.
I notice that more and more people are putting audio on youtube, with some
kind of a cover picture to make it a video.
However that does not need to change your categories, which look good.
--Andrew

**Comment by andrewfn** [comment]
Take a look and see what you think.

**Comment by joshgrossman** [comment]
Thanks Andrew - looks good to me!  Just one minor addition.  For the video links, beside "Paste a link to either YouTube or Vimeo”, could you indicate the required link format (i.e. should it be https://youtu.be/1q1zkCfP1a4 <https://youtu.be/1q1zkCfP1a4> or https://vimeo.com/302055120 <https://vimeo.com/302055120> or something different?).

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Toronto in 2019 (BizBash)

**Comment by andrewfn** [comment]
Good point. How does this look now?

**Comment by joshgrossman** [comment]
That works!  Thanks.

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Toronto in 2019 (BizBash)
