### ISSUE TITLE
new corner graphic

### ISSUE THREAD

**Issue by brianblain** [jazzto/2018#2]
I created a new page

http://torontojazz.com/yorkville-free-shows

can you link the new graphic to that page...and perhaps you could see if you can't make it a little more consistent with our style.  I was just grabbing HTML from a word doc...

(ie big gaps between paragra
![website_corner_template](https://user-images.githubusercontent.com/11864078/39686794-2bb818ca-5199-11e8-87ef-ea17ee6d392a.png)
phs)

**Comment by andrewfn** [comment]
Ok I'll take a look

**Comment by andrewfn** [comment]
Done
