### ISSUE TITLE
new OLG ad

### ISSUE THREAD

**Issue by brianblain** [jazzto/2018#3]
![en_olg237_tdtorontojazzfestival_159x448_c01](https://user-images.githubusercontent.com/11864078/39720549-bbe3c0e0-520a-11e8-97f1-5eab987172dc.jpg)

and here is the link:   http://about.olg.ca/all-for-here/

**Comment by brianblain** [comment]
stand by - OLG is sending an updated ad

**Comment by brianblain** [comment]
here is their new ad:

[OLG 237_TDTorontoJazzFestival_159x448_mk05.pdf](https://github.com/jazzto/2018/files/1989846/OLG.237_TDTorontoJazzFestival_159x448_mk05.pdf)

**Comment by andrewfn** [comment]
I have made the new ad active --i assume that is what you want.
Here's what it looks like: http://torontojazz.com/sites/default/files/field/image/olg-banner-2018.png
