### ISSUE TITLE
Add series name

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2018#4]
Could you please add the following to the list of "series" in the concert creation page:

The Jazz Musician Intensive

Is that something I can do in the future, or does it need to be done by one of you folks?

Josh

**Comment by andrewfn** [comment]
Added.
It would be tricky to show you how to do it and set up access permissions, but I'm happy to keep doing it.

**Comment by joshgrossman** [comment]
Thanks!

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27

TD Toronto Jazz Festival Ranked #1 Music Event in Toronto in 2017 (BizBash)
