### ISSUE TITLE
new sponsor logo

### ISSUE THREAD

**Issue by brianblain** [jazzto/2018#7]
can you please add the Yamaha logo attached to the rotation.  I have re-sized according to the last one but not sure what to do next. Thanks
![yamaha_logo_white-j](https://user-images.githubusercontent.com/11864078/41002708-9bcc887a-68e2-11e8-9ff9-56fcf0014243.jpg)

**Comment by andrewfn** [comment]
Hi Brian,
All you have to do is to go to the ads page: http://torontojazz.com/admin/content/simpleads
Select group 2 (small ads) and press filter
Then you can edit the current Yamaha ad and change the image.
If you have trouble with this, let me know and I'll do it.

**Comment by brianblain** [comment]
Got it!  B
